### ISSUE TITLE
[CHANGE] New Font Height for Long Text

### ISSUE THREAD

**Issue by hujikol** [sunflower-land/sunflower-land#1760]
## How the Feature is Currently Working

1. Currently, the new font has narrow letter space and line height, which brings a bit of trouble in reading a long-running text or a paragraph in the game.
2. We also still have inconsistency within text type and decoration, 

   ![image](https://user-images.githubusercontent.com/12151051/204022954-d44ba7aa-a9db-4ba3-9dc1-6a298af7a2eb.png)

## How the Feature Should Be Changed

1. add new CSS text type for only a long paragraph and not for labels or button
2. whether it indicated a link or a title, standardization is a must for further use

   ![image](https://user-images.githubusercontent.com/12151051/204025456-7f6d4009-899d-4437-9e6d-7d834aa7e22a.png)

## Contributors

I could do some adjustments to the letter space and the line height, and also do the standardization for text type

## Technical Requirements

Provide clear, step-by-step instructions for HOW this change will be implemented. Keep sentences short, and use sub-bullets if needed. Developers should be able to look at this list and effortlessly start programming the new feature change.

1. Add more text config other than xxs, xs, sm, base, etc...
   > my approach is going to name it by something like `text-body` , `text-tittle`, `text-subtitle`, `text-link`

<details>
  <summary>CSS Like wise</summary>

  ### tailwind.config.js
  ```css
      tiny: [
        "0.9rem",
        {
          lineHeight: "1.125rem",
        },
      ],
      smaller: [
        "1rem",
        {
          lineHeight: "1.25rem",
        },
      ],
      small: [
        "1.275rem",
        {
          lineHeight: "1.593rem",
        },
      ],
      normal: [
        "1.6rem",
        {
          lineHeight: "2rem",
          letterSpace: "-0.3px",
        },
      ],

      large: [
        "1.725rem",
        {
          lineHeight: "2.156rem",
        },
      ],
      larger: [
        "3.25rem",
        {
          lineHeight: "4.062rem",
        },
      ],
  ```
</details>
<br/><br/>
2. we could also add more color states (i.e. `success`, `error`, `warning`, `info`)

### Backend Updates Needed

N/A

### Smart Contract Updates Needed

N/A

## UI/UX Design Requirements

1. Some padding and margin adjustment on long-running text or paragraph
2. Add custom letter spacing and line height

## Assets Needed:

N/A
